import { packager } from '@electron/packager';
import { checkPrivacy } from './check-privacy.mjs';
function requireCleanPrivacy(artifacts=false){const result=checkPrivacy({artifacts});if(result.failures.length)throw new Error('Privacy check failed: '+result.failures.map(f=>`${f.file} (${f.rules.join(', ')})`).join('; '));}
requireCleanPrivacy();
import { cpSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { resolve, join } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const {version}=JSON.parse(readFileSync(join(root,'package.json'),'utf8'));
const stage=join(root,'build/app-stage');
// This directory is exclusively generated by this script.
rmSync(stage,{recursive:true,force:true});mkdirSync(stage,{recursive:true});
for(const dir of ['dist','core','electron','docs'])cpSync(join(root,dir),join(stage,dir),{recursive:true});
mkdirSync(join(stage,'scripts'),{recursive:true});cpSync(join(root,'scripts/aster-run.mjs'),join(stage,'scripts/aster-run.mjs'));
mkdirSync(join(stage,'build'),{recursive:true});cpSync(join(root,'build/tray.png'),join(stage,'build/tray.png'));
for(const file of ['THIRD_PARTY_NOTICES.md','THIRD_PARTY_LICENSES.txt','README.md','AGENTS.md'])cpSync(join(root,file),join(stage,file));
writeFileSync(join(stage,'package.json'),JSON.stringify({name:'aster-pet',productName:'Aster',version,type:'module',main:'electron/main.mjs'},null,2));
const electronVersion=JSON.parse(readFileSync(join(root,'node_modules/electron/package.json'),'utf8')).version;
const result=await packager({dir:stage,name:'Aster',platform:'darwin',arch:process.arch,electronVersion,out:join(root,'release'),overwrite:true,prune:false,icon:join(root,'build/Aster.icns'),appBundleId:'local.aster.companion',appCategoryType:'public.app-category.productivity',asar:true});
requireCleanPrivacy(true);
console.log('Packaged:',result.join('\n'));
